[OnlineSubsystemMcp.Xmpp]
bUseSSL=true
ServerAddr="ws://127.0.0.1:80"
ServerPort=80

[OnlineSubsystemMcp.Xmpp Prod]
bUseSSL=true
ServerAddr="ws://127.0.0.1:80"
ServerPort=80

[ConsoleVariables]
n.VerifyPeer=0
FortMatchmakingV2.ContentBeaconFailureCancelsMatchmaking=0
Fort.ShutdownWhenContentBeaconFails=0
FortMatchmakingV2.EnableContentBeacon=0


[OnlineSubsystemMcp.OnlineWaitingRoomMcp]
bEnabled=false
ServiceName="waitingroom"
GracePeriod=300
RetryConfigUrl="https://s3-us-west-1.amazonaws.com/launcher-resources/waitingroom"

[OnlineSubsystemMcp]
bUsePartySystemV2=true

[OnlineSubsystemMcp.OnlinePartySystemMcpAdapter]
bUsePartySystemV2=true

[CrashContextProperties]
CrashReportClientRichText=NSLOCTEXT("FortGlobals", "FortniteCrashReportClientText", "Fortnite has crashed please contact PROJECT NAME staff.")

[/Script/Qos.QosRegionManager]
NumTestsPerRegion=1
PingTimeout=3.0
!RegionDefinitions=ClearArray
+RegionDefinitions=(DisplayName="More Momentum Auto", RegionId="AutoRegion", bEnabled=true, bVisible=true, bAutoAssignable=true)
;+RegionDefinitions=(DisplayName="Na-East", RegionId="NAE", bEnabled=true, bVisible=true, bAutoAssignable=false) # REMOVE THE ; IF YOUR USING THIS REGION
;+RegionDefinitions=(DisplayName="Na-West", RegionId="NAW", bEnabled=true, bVisible=true, bAutoAssignable=false) # REMOVE THE ; IF YOUR USING THIS REGION
;+RegionDefinitions=(DisplayName="Oceania", RegionId="OCE", bEnabled=true, bVisible=true, bAutoAssignable=false) # REMOVE THE ; IF YOUR USING THIS REGION
+RegionDefinitions=(DisplayName="More Momentum EU", RegionId="EU", bEnabled=true, bVisible=true, bAutoAssignable=false)
;+RegionDefinitions=(DisplayName="Me", RegionId="ME", bEnabled=true, bVisible=true, bAutoAssignable=false) # REMOVE THE ; IF YOUR USING THIS REGION
;+RegionDefinitions=(DisplayName="Brazil", RegionId="BR", bEnabled=true, bVisible=true, bAutoAssignable=false) # REMOVE THE ; IF YOUR USING THIS REGION

[XMPP]
bEnableWebsockets=true

[LwsWebSocket]
bDisableCertValidation=true

[/Script/Engine.NetworkSettings]
n.VerifyPeer=false